syntax = "v1.0";
package com.ecust;
appid = 1002;

class HelloRequest{
    string name;
    int16 myInt16;
    int32 myInt32;
    float myFloat;
    double myDouble;
    boolean myBoolean
    Map<int16,double> myMap;
    List<int32> myList;
}

class HelloResponse{
    string name;
    int16 myInt16;
    int32 myInt32;
    float myFloat;
    double myDouble;
    boolean myBoolean
    Map<int16,double> myMap;
    List<int32> myList;
}

class Hello2Request{
    string name;
    int16 myInt16;
    int32 myInt32;
    float myFloat;
    double myDouble;
    boolean myBoolean
    Map<int16,double> myMap;
    List<int32> myList;
}

class Hello2Response{
    string name;
    int16 myInt16;
    int32 myInt32;
    float myFloat;
    double myDouble;
    boolean myBoolean
    Map<int16,double> myMap;
    List<int32> myList;
}

service Greeter{
    HelloResponse sayHello(HelloRequest request);
    Hello2Response sayHello2(Hello2Request request);
}





